In [2]:
import pandas as pd

In [4]:
df = pd.read_csv('datasets_4123_6408_framingham.csv')


In [6]:
df.head()


male  age  education  currentSmoker  cigsPerDay  BPMeds  prevalentStroke  \
0     1   39        4.0              0         0.0     0.0                0   
1     0   46        2.0              0         0.0     0.0                0   
2     1   48        1.0              1        20.0     0.0                0   
3     0   61        3.0              1        30.0     0.0                0   
4     0   46        3.0              1        23.0     0.0                0   

   prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  heartRate  glucose  \
0             0         0    195.0  106.0   70.0  26.97       80.0     77.0   
1             0         0    250.0  121.0   81.0  28.73       95.0     76.0   
2             0         0    245.0  127.5   80.0  25.34       75.0     70.0   
3             1         0    225.0  150.0   95.0  28.58       65.0    103.0   
4             0         0    285.0  130.0   84.0  23.10       85.0     85.0   

   TenYearCHD  
0           0  
1           0  
2           0  
3           1  
4           0

In [8]:
df = df.drop(columns=['education'])

In [10]:
df.isnull().sum()

male                 0
age                  0
currentSmoker        0
cigsPerDay          29
BPMeds              53
prevalentStroke      0
prevalentHyp         0
diabetes             0
totChol             50
sysBP                0
diaBP                0
BMI                 19
heartRate            1
glucose            388
TenYearCHD           0
dtype: int64

In [12]:
df.shape

(4240, 15)

In [14]:
bin_cols = ["male", "currentSmoker", "prevalentStroke", "prevalentHyp", "diabetes"z,""]
# Fill missing values for binary features with the most frequent value (mode)
for col in bin_cols:
mode_val = df[col].mode()[0]
df[col].fillna(mode_val, inplace=True)

SyntaxError: invalid syntax. Perhaps you forgot a comma? (3985332243.py, line 1)

In [20]:
bin_cols = ["male", "currentSmoker", "prevalentStroke", "prevalentHyp", "diabetes"]
# Fill missing values for binary features with the most frequent value (mode)
for col in bin_cols:
    mode_val = df[col].mode()[0]
    df[col].fillna(mode_val, inplace=True)

C:\Users\pande\AppData\Local\Temp\ipykernel_11256\3334308813.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(mode_val, inplace=True)
C:\Users\pande\AppData\Local\Temp\ipykernel_11256\3334308813.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when

In [22]:
df.isnull().sum()

male                 0
age                  0
currentSmoker        0
cigsPerDay          29
BPMeds              53
prevalentStroke      0
prevalentHyp         0
diabetes             0
totChol             50
sysBP                0
diaBP                0
BMI                 19
heartRate            1
glucose            388
TenYearCHD           0
dtype: int64

In [26]:
import numpy as np
# Fill missing values for numeric features
numeric_cols = ["cigsPerDay", "BPMeds", "totChol", "BMI", "heartRate", "glucose"]
for col in numeric_cols:
    median_val = df[col].median()
    df[col].fillna(median_val, inplace=True)

C:\Users\pande\AppData\Local\Temp\ipykernel_11256\2544170342.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(median_val, inplace=True)


In [28]:
df.isnull().sum()

male               0
age                0
currentSmoker      0
cigsPerDay         0
BPMeds             0
prevalentStroke    0
prevalentHyp       0
diabetes           0
totChol            0
sysBP              0
diaBP              0
BMI                0
heartRate          0
glucose            0
TenYearCHD         0
dtype: int64

In [30]:
df['TenYearCHD'].value_counts()


TenYearCHD
0    3596
1     644
Name: count, dtype: int64

In [32]:
from sklearn.utils import resample
# Separate majority and minority classes
df_majority = df[df['TenYearCHD'] == 0]
df_minority = df[df['TenYearCHD'] == 1]
# Upsample minority class
df_minority_upsampled = resample(df_minority,replace=True, # Sample with replacement
                                 n_samples=len(df_majority), # To match majority class
random_state=42) # Reproducible results
# Combine majority class with upsampled minority class
df_balanced = pd.concat([df_majority, df_minority_upsampled])

In [34]:
df_balanced['TenYearCHD'].value_counts()

TenYearCHD
0    3596
1    3596
Name: count, dtype: int64

In [36]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
# Separate features (X) and target variable (y)
X = df_balanced.drop(columns=['TenYearCHD'])
y = df_balanced['TenYearCHD']
# Split the data into training and testing sets (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [38]:
x_train


NameError: name 'x_train' is not defined

In [40]:
X_train

male  age  currentSmoker  cigsPerDay  BPMeds  prevalentStroke  \
1905     0   64              0         0.0     0.0                0   
2075     0   37              1        20.0     0.0                0   
1128     0   63              1        10.0     0.0                0   
1782     0   65              0         0.0     0.0                0   
241      1   65              1        15.0     0.0                0   
...    ...  ...            ...         ...     ...              ...   
624      1   63              1        20.0     0.0                0   
485      1   54              1        40.0     0.0                0   
4232     1   68              0         0.0     0.0                0   
952      1   66              1        30.0     0.0                0   
1030     1   45              1        20.0     0.0                0   

      prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  heartRate  glucose  
1905             1         0    229.0  145.0   85.0  29.67       70.0     74.0  
2075             0         0    166.0  112.0   73.5  21.64       75.0     93.0  
1128             1         0    236.0  189.0  103.0  27.91       60.0     74.0  
1782             1         0    245.0  171.0   89.0  23.07       82.0     93.0  
241              1         0    219.0  148.0   90.0  29.35       77.0     97.0  
...            ...       ...      ...    ...    ...    ...        ...      ...  
624              1         0    269.0  180.0  101.0  24.42       72.0     84.0  
485              0         0    230.0  145.0   90.0  25.72       75.0     85.0  
4232             1         0    176.0  168.0   97.0  23.14       60.0     79.0  
952              0         1    234.0  114.5   62.5  28.62       75.0    216.0  
1030             0         1    279.0  138.0   86.0  30.63       80.0    144.0  

[5753 rows x 14 columns]

In [42]:
scaler = StandardScaler()
# Fit scaler to training data and transform both training and testing data
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [44]:
X_train_scaled

array([[-0.94172615,  1.4582083 , -1.02624378, ...,  0.840088  ,
        -0.50731448, -0.34072887],
       [-0.94172615, -1.66694628,  0.97442734, ..., -1.050363  ,
        -0.0898974 ,  0.25133934],
       [-0.94172615,  1.34246184,  0.97442734, ...,  0.42574258,
        -1.34214864, -0.34072887],
       ...,
       [ 1.06187982,  1.92119417, -1.02624378, ..., -0.6972277 ,
        -1.34214864, -0.18492145],
       [ 1.06187982,  1.68970124,  0.97442734, ...,  0.59289329,
        -0.0898974 ,  4.08420194],
       [ 1.06187982, -0.74097455,  0.97442734, ...,  1.0660946 ,
         0.32751968,  1.84057505]])

In [46]:
X_train

male  age  currentSmoker  cigsPerDay  BPMeds  prevalentStroke  \
1905     0   64              0         0.0     0.0                0   
2075     0   37              1        20.0     0.0                0   
1128     0   63              1        10.0     0.0                0   
1782     0   65              0         0.0     0.0                0   
241      1   65              1        15.0     0.0                0   
...    ...  ...            ...         ...     ...              ...   
624      1   63              1        20.0     0.0                0   
485      1   54              1        40.0     0.0                0   
4232     1   68              0         0.0     0.0                0   
952      1   66              1        30.0     0.0                0   
1030     1   45              1        20.0     0.0                0   

      prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  heartRate  glucose  
1905             1         0    229.0  145.0   85.0  29.67       70.0     74.0  
2075             0         0    166.0  112.0   73.5  21.64       75.0     93.0  
1128             1         0    236.0  189.0  103.0  27.91       60.0     74.0  
1782             1         0    245.0  171.0   89.0  23.07       82.0     93.0  
241              1         0    219.0  148.0   90.0  29.35       77.0     97.0  
...            ...       ...      ...    ...    ...    ...        ...      ...  
624              1         0    269.0  180.0  101.0  24.42       72.0     84.0  
485              0         0    230.0  145.0   90.0  25.72       75.0     85.0  
4232             1         0    176.0  168.0   97.0  23.14       60.0     79.0  
952              0         1    234.0  114.5   62.5  28.62       75.0    216.0  
1030             0         1    279.0  138.0   86.0  30.63       80.0    144.0  

[5753 rows x 14 columns]

In [48]:
from sklearn.ensemble import RandomForestClassifier

rf_model=RandomForestClassifier()

rf_model.fit(X_train_scaled,y_train)

y_pred=rf_model.predict(X_test_scaled)

In [50]:
y_pred

array([1, 1, 1, ..., 1, 1, 1], dtype=int64)

In [52]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [54]:
accuracy_score(y_test, y_pred)

0.9715079916608756

In [56]:
confusion_matrix(y_test,y_pred)

array([[699,  36],
       [  5, 699]], dtype=int64)

In [58]:
print(classification_report(y_test,y_pred)) 

              precision    recall  f1-score   support

           0       0.99      0.95      0.97       735
           1       0.95      0.99      0.97       704

    accuracy                           0.97      1439
   macro avg       0.97      0.97      0.97      1439
weighted avg       0.97      0.97      0.97      1439



In [60]:
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report, confusion_matrix

ModuleNotFoundError: No module named 'xgboost'

In [62]:
import xgboost

ModuleNotFoundError: No module named 'xgboost'

In [64]:
import XGBoost

ModuleNotFoundError: No module named 'XGBoost'

In [66]:
import XGboost

ModuleNotFoundError: No module named 'XGboost'

In [68]:
!pip install xgboost

   ---------------------------------------- 0.0/124.9 MB ? eta -:--:--
   - -------------------------------------- 3.1/124.9 MB 23.1 MB/s eta 0:00:06
   - -------------------------------------- 4.5/124.9 MB 19.2 MB/s eta 0:00:07
   -- ------------------------------------- 6.3/124.9 MB 11.4 MB/s eta 0:00:11
   -- ------------------------------------- 6.8/124.9 MB 9.1 MB/s eta 0:00:13
   --- ------------------------------------ 10.7/124.9 MB 10.8 MB/s eta 0:00:11
   ---- ----------------------------------- 13.1/124.9 MB 11.1 MB/s eta 0:00:11
   ----- ---------------------------------- 15.7/124.9 MB 11.4 MB/s eta 0:00:10
   ----- ---------------------------------- 18.4/124.9 MB 11.7 MB/s eta 0:00:10
   ------ --------------------------------- 21.2/124.9 MB 11.8 MB/s eta 0:00:09
   ------- -------------------------------- 23.9/124.9 MB 12.0 MB/s eta 0:00:09
   -------- ------------------------------- 26.5/124.9 MB 12.1 MB/s eta 0:00:09
   --------- ------------------------------ 29.1/124.9

In [69]:
import xgboost

In [72]:
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report, confusion_matrix

In [74]:
classifiers = [
RandomForestClassifier(),
AdaBoostClassifier(),
GradientBoostingClassifier(),
LogisticRegression(),
SVC(),
KNeighborsClassifier(),
DecisionTreeClassifier(),
GaussianNB(),
XGBClassifier()
]

In [76]:
results = {}

In [80]:
for clf in classifiers:
    clf_name = clf.__class__.__name__
    clf.fit(X_train_scaled, y_train)
    y_pred = clf.predict(X_test_scaled)
# Calculate accuracy
    accuracy = accuracy_score(y_test, y_pred)
    print(f"{clf_name} Accuracy: {accuracy}")
# Classification report
    print(f"Classification Report for {clf_name}:")
    print(classification_report(y_test, y_pred))
# Confusion matrix
    print(f"Confusion Matrix for {clf_name}:")
    print(confusion_matrix(y_test, y_pred))
    print("="*50)

RandomForestClassifier Accuracy: 0.9735927727588604
Classification Report for RandomForestClassifier:
              precision    recall  f1-score   support

           0       0.99      0.96      0.97       735
           1       0.95      0.99      0.97       704

    accuracy                           0.97      1439
   macro avg       0.97      0.97      0.97      1439
weighted avg       0.97      0.97      0.97      1439

Confusion Matrix for RandomForestClassifier:
[[702  33]
 [  5 699]]


C:\ProgramData\anaconda3\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(


AdaBoostClassifier Accuracy: 0.6719944405837387
Classification Report for AdaBoostClassifier:
              precision    recall  f1-score   support

           0       0.69      0.66      0.67       735
           1       0.66      0.68      0.67       704

    accuracy                           0.67      1439
   macro avg       0.67      0.67      0.67      1439
weighted avg       0.67      0.67      0.67      1439

Confusion Matrix for AdaBoostClassifier:
[[486 249]
 [223 481]]
GradientBoostingClassifier Accuracy: 0.7289784572619875
Classification Report for GradientBoostingClassifier:
              precision    recall  f1-score   support

           0       0.76      0.69      0.72       735
           1       0.70      0.77      0.74       704

    accuracy                           0.73      1439
   macro avg       0.73      0.73      0.73      1439
weighted avg       0.73      0.73      0.73      1439

Confusion Matrix for GradientBoostingClassifier:
[[508 227]
 [163 541]]
Logist

In [82]:
results_df = pd.DataFrame(columns=['Model', 'Accuracy', 'F1-Score', 'Precision', 'Recall'])

In [94]:
for clf in classifiers:
    clf_name = clf.__class__.__name__
    clf.fit(X_train_scaled, y_train)
    y_pred = clf.predict(X_test_scaled)
    
    # Calculate evaluation metrics
    accuracy = accuracy_score(y_test, y_pred)
    report = classification_report(y_test, y_pred, output_dict=True)
    f1_score = report['weighted avg']['f1-score']
    precision = report['weighted avg']['precision']
    recall = report['weighted avg']['recall']
    
    # Append results to DataFrame
    results_df = pd.concat([results_df,pd.DataFrame([{
        'Model': clf_name,
        'Accuracy': accuracy,
        'F1-Score': f1_score,
        'Precision': precision,
        'Recall': recall}])], ignore_index=True)


C:\Users\pande\AppData\Local\Temp\ipykernel_11256\27216665.py:14: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results_df = pd.concat([results_df,pd.DataFrame([{
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(


In [96]:
results_df

Model  Accuracy  F1-Score  Precision    Recall
0      RandomForestClassifier  0.967338  0.967335   0.968612  0.967338
1          AdaBoostClassifier  0.671994  0.672015   0.672474  0.671994
2  GradientBoostingClassifier  0.728978  0.728702   0.731320  0.728978
3          LogisticRegression  0.658791  0.658830   0.659053  0.658791
4                         SVC  0.683113  0.683126   0.683656  0.683113
5        KNeighborsClassifier  0.787352  0.783833   0.812481  0.787352
6      DecisionTreeClassifier  0.915914  0.915520   0.927041  0.915914
7                  GaussianNB  0.583044  0.530092   0.635597  0.583044
8               XGBClassifier  0.906185  0.905977   0.912148  0.906185

In [98]:
rf_classifier = RandomForestClassifier()
# Train the RandomForestClassifier
rf_classifier.fit(X_train_scaled, y_train)
# Predict on the test set
y_pred_rf = rf_classifier.predict(X_test_scaled)
# Calculate accuracy
accuracy_rf = accuracy_score(y_test, y_pred_rf)
print("Random Forest Classifier Accuracy:", accuracy_rf)
# Classification report
print("Classification Report for Random Forest Classifier:")
print(classification_report(y_test, y_pred_rf))
# Confusion matrix
print("Confusion Matrix for Random Forest Classifier:")
print(confusion_matrix(y_test, y_pred_rf))

Random Forest Classifier Accuracy: 0.9742876997915219
Classification Report for Random Forest Classifier:
              precision    recall  f1-score   support

           0       0.99      0.96      0.97       735
           1       0.96      0.99      0.97       704

    accuracy                           0.97      1439
   macro avg       0.97      0.97      0.97      1439
weighted avg       0.97      0.97      0.97      1439

Confusion Matrix for Random Forest Classifier:
[[703  32]
 [  5 699]]


In [100]:
print("predcted class ",rf_classifier.predict(X_test_scaled[10].reshape(1,-1))[0])
print("actual class ", y_test.iloc[10])


predcted class  0
actual class  0
